# =============================
# APP
# =============================

spring.application.name=nguyenhoangluan
server.port=8080

# =============================
# DATABASE MYSQL (LARAGON)
# =============================

spring.datasource.url=jdbc:mysql://localhost:3306/webbanhang?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =============================
# JPA / HIBERNATE
# =============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=true

# =============================
# THYMELEAF
# =============================

spring.thymeleaf.cache=false

# =============================
# OPENAI API
# =============================

openai.api.key=sk-xxxxxxxxxxxxxxxxxxxxxxxx

# =============================
# LOG
# =============================

spring.main.banner-mode=off